### ISSUE TITLE
Downstream Service Error

### ISSUE THREAD

**Issue by JosiahThobejane** [2Checkout/2checkout-java#12]
Hi,

I am trying to stop a sale using the Java SDK in this way:
`Sale sale = TwocheckoutSale.retrieve(orderNumber);
TwocheckoutResponse response= sale.stop();
if(!response.getResponseCode().equalsIgnoreCase("OK"))
{
throw new Exception(response.getResponseCode()+" : "+response.getResponseMessage() +". ProfileID :  "+orderNumber);
}
return response;`

When I execute that function I get this Exception:
`com.twocheckout.TwocheckoutException: Downstream Service Error`

What could be the issue?

> Due to the nature of the emergency of the work needing to be done, I have moved over to use your Avangate REST 3.0 API, which works fine.

**Comment by craigchristenson** [comment]
Hi Josiah, I was not able to replicate this error but while testing I did find a potential issue with the sale retrieve data marshalling that I have corrected on master and uploaded a new JAR. So that I can further troubleshoot can you pull down the most recent `2checkout-java.jar` to test and let me know which environment you are hitting (sandbox or production). Also can you let me know if you are hitting this exception on the ` TwocheckoutSale.retrieve(orderNumber)` or `sale.stop()` method. Thanks for you help with this.
- Craig
